language: python
python:
  - '3.5'
before_install:
  - sudo apt-get install python-software-properties
  - sudo apt-add-repository ppa:brightbox/ruby-ng
  - sudo apt-get update
  - sudo apt-get install ruby2.0.0 ruby-switch
  - sudo ruby-switch --set ruby2.0.0
  - bundle install
  - pip3 install pytest
script: source run_ruby_and_python_tests.sh

# language: python
# python:
#   - '3.5'
# before_install:
#   - pip install pytest
# script:
#   - py.test python/
